# Generated by Django 4.2.1 on 2023-10-02 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('monto_boleta', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha_boleta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_esp', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nom_esp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_cli', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dv_cli', models.CharField(max_length=1)),
                ('pnom_cli', models.CharField(max_length=40)),
                ('snom_cli', models.CharField(blank=True, max_length=40, null=True)),
                ('apaterno_cli', models.CharField(max_length=40)),
                ('amaterno_cli', models.CharField(max_length=40)),
                ('email_cli', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_cli', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagoAtencion',
            fields=[
                ('id_ate', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_ate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_cancelar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('rut_sec', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dv_sec', models.CharField(max_length=1)),
                ('pnom_sec', models.CharField(max_length=20)),
                ('snom_sec', models.CharField(blank=True, max_length=20, null=True)),
                ('apaterno_sec', models.CharField(max_length=40)),
                ('amaterno_sec', models.CharField(max_length=20)),
                ('fecnac_sec', models.DateField()),
                ('honorario_sec', models.DecimalField(decimal_places=2, max_digits=20)),
                ('email_sec', models.EmailField(max_length=254)),
                ('telefono_sec', models.PositiveIntegerField()),
                ('feccont_sec', models.DateField()),
                ('email_user', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email_user', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password_user', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rut_med', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dv_med', models.CharField(max_length=1)),
                ('pnombre_med', models.CharField(max_length=20)),
                ('snombre_med', models.CharField(blank=True, max_length=20, null=True)),
                ('apaterno_med', models.CharField(max_length=40)),
                ('amaterno_med', models.CharField(max_length=20)),
                ('fecnac_med', models.DateField()),
                ('honorario_med', models.DecimalField(decimal_places=2, max_digits=20)),
                ('email_med', models.EmailField(max_length=254)),
                ('telefono_med', models.PositiveIntegerField()),
                ('feccont_med', models.DateField()),
                ('email_user', models.CharField(max_length=10, unique=True)),
                ('rut_sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroMedicoApp.secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_inic_esp', models.DateField()),
                ('id_esp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroMedicoApp.especialidad')),
                ('rut_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroMedicoApp.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_ate', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha_ate', models.DateField(default=django.utils.timezone.now)),
                ('hora_ate', models.PositiveIntegerField(default=0)),
                ('precio_ate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bono_ate', models.CharField(default='valor_predeterminado', max_length=20)),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroMedicoApp.boleta')),
                ('id_esp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroMedicoApp.especialidad')),
                ('rut_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroMedicoApp.paciente')),
                ('rut_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='centroMedicoApp.medico')),
                ('rut_med1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_asistidas', to='centroMedicoApp.medico')),
            ],
            options={
                'unique_together': {('id_ate', 'rut_med1', 'id_esp')},
            },
        ),
    ]
