# Generated by Django 4.2.1 on 2023-10-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='hora_ate',
            field=models.TimeField(default=0),
        ),
    ]
