# Generated by Django 4.2.1 on 2023-10-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0003_alter_atencion_id_ate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='precio_ate',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='monto_boleta',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='honorario_med',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pagoatencion',
            name='monto_ate',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pagoatencion',
            name='monto_cancelar',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='honorario_sec',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
