# Generated by Django 4.2.6 on 2023-10-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0004_alter_atencion_precio_ate_alter_boleta_monto_boleta_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='atencion',
            unique_together={('id_ate', 'id_esp')},
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='rut_med1',
        ),
    ]
