# Generated by Django 4.2.6 on 2023-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0005_alter_atencion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='monto_esp',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='bono_ate',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
