# Generated by Django 4.2.6 on 2023-10-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0006_especialidad_monto_esp_alter_atencion_bono_ate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nom_esp',
            field=models.CharField(max_length=40),
        ),
    ]
