# Generated by Django 4.2.6 on 2023-10-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0008_alter_medico_email_user_alter_secretaria_email_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='id_boleta',
            new_name='id_boleta_ate',
        ),
        migrations.RenameField(
            model_name='atencion',
            old_name='id_esp',
            new_name='id_esp_ate',
        ),
        migrations.RenameField(
            model_name='atencion',
            old_name='rut_cli',
            new_name='rut_cli_ate',
        ),
        migrations.RenameField(
            model_name='atencion',
            old_name='rut_med',
            new_name='rut_med_ate',
        ),
        migrations.RenameField(
            model_name='especialidadmedico',
            old_name='id_esp',
            new_name='id_esp_esp',
        ),
        migrations.RenameField(
            model_name='especialidadmedico',
            old_name='rut_med',
            new_name='rut_med_esp',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='rut_sec',
            new_name='rut_sec_med',
        ),
        migrations.AlterUniqueTogether(
            name='atencion',
            unique_together={('id_ate', 'id_esp_ate')},
        ),
    ]
