# Generated by Django 4.2.6 on 2023-10-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0009_rename_id_boleta_atencion_id_boleta_ate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='id_boleta_ate',
            new_name='id_boleta',
        ),
        migrations.RenameField(
            model_name='atencion',
            old_name='id_esp_ate',
            new_name='id_esp',
        ),
        migrations.RenameField(
            model_name='atencion',
            old_name='rut_cli_ate',
            new_name='rut_cli',
        ),
        migrations.RenameField(
            model_name='atencion',
            old_name='rut_med_ate',
            new_name='rut_med',
        ),
        migrations.RenameField(
            model_name='especialidadmedico',
            old_name='id_esp_esp',
            new_name='id_esp',
        ),
        migrations.RenameField(
            model_name='especialidadmedico',
            old_name='rut_med_esp',
            new_name='rut_med',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='rut_sec_med',
            new_name='rut_sec',
        ),
        migrations.AlterUniqueTogether(
            name='atencion',
            unique_together={('id_ate', 'id_esp')},
        ),
    ]
