# Generated by Django 4.2.6 on 2023-10-26 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0010_rename_id_boleta_ate_atencion_id_boleta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_user',
            new_name='id_user',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='email_user',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='email_user',
        ),
        migrations.AddField(
            model_name='medico',
            name='id_user',
            field=models.ForeignKey(default=models.PositiveIntegerField(primary_key=True, serialize=False), on_delete=django.db.models.deletion.CASCADE, to='centroMedicoApp.user'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='id_user',
            field=models.ForeignKey(default=models.PositiveIntegerField(primary_key=True, serialize=False), on_delete=django.db.models.deletion.CASCADE, to='centroMedicoApp.user'),
        ),
    ]
