# Generated by Django 4.2.6 on 2023-10-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0014_alter_medico_id_user_alter_secretaria_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='id_user',
            field=models.ForeignKey(default=models.F('rut_med'), on_delete=django.db.models.deletion.CASCADE, to='centroMedicoApp.user'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='id_user',
            field=models.ForeignKey(default=models.F('rut_sec'), on_delete=django.db.models.deletion.CASCADE, to='centroMedicoApp.user'),
        ),
    ]
