# Generated by Django 4.2.6 on 2023-10-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0015_alter_medico_id_user_alter_secretaria_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
