# Generated by Django 4.2.6 on 2023-10-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0018_rename_id_user_user_rut_remove_medico_id_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
