# Generated by Django 4.2.6 on 2023-10-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0019_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='medico',
            name='user',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='usercentro',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroMedicoApp.medico'),
        ),
    ]
