# Generated by Django 4.2.6 on 2023-10-30 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('centroMedicoApp', '0020_usercentro_remove_medico_user_remove_secretaria_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercentro',
            name='rut',
        ),
        migrations.AddField(
            model_name='usercentro',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='usercentro',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
