# Generated by Django 4.2.6 on 2023-11-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0022_diaslaborables_medico_hora_fin_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='dias_laborables',
            field=models.ManyToManyField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], to='centroMedicoApp.diaslaborables'),
        ),
    ]
