# Generated by Django 4.2.6 on 2023-11-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0023_alter_medico_dias_laborables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='dias_laborables',
        ),
        migrations.AddField(
            model_name='medico',
            name='dias_laborales',
            field=models.ManyToManyField(to='centroMedicoApp.diaslaborables'),
        ),
    ]
