# Generated by Django 4.2.6 on 2023-11-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0024_remove_medico_dias_laborables_medico_dias_laborales'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='disponible_ate',
            field=models.BooleanField(default=True),
        ),
    ]
