# Generated by Django 4.2.6 on 2023-11-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroMedicoApp', '0025_atencion_disponible_ate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercentro',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
